<?php
$pages = [
  [
    'label' => 'About',
    'file' => 'index.php',
    'desc' => 'Project overview and comparison points.'
  ],
  [
    'label' => 'Baseline Lazy',
    'file' => 'baseline-lazy.php',
    'desc' => 'JPG hero image with <code>loading="lazy"</code>.'
  ],
  [
    'label' => 'Baseline Eager',
    'file' => 'baseline-eager.php',
    'desc' => 'JPG hero image with <code>loading="eager"</code>.'
  ],
  [
    'label' => 'LQIP No Blur',
    'file' => 'lqip-no-blur.php',
    'desc' => 'A two-level LQIP technique: a tiny base64 placeholder, then a display-size LQIP-LCP image at 0.055 BPP, then the full-res image.'
  ],
  [
    'label' => 'LQIP with Blur',
    'file' => 'lqip-blur.php',
    'desc' => 'A two-level LQIP technique: a tiny base64 placeholder, then a display-size LQIP-LCP image at 0.055 BPP, then the full-res image, with CSS blur on placeholder.'
  ],
  [
    'label' => 'SQIP',
    'file' => 'sqip.php',
    'desc' => 'SVG placeholder generated by SQIP, swaps to full-res hero image.'
  ],
  [
    'label' => 'CSS-only LQIP',
    'file' => 'css-lqip.php',
    'desc' => 'Pure CSS LQIP: dominant color or gradient as background, hero image fades in on top.'
  ],
  [
    'label' => 'Credits',
    'file' => 'credits.php',
    'desc' => 'Credits and references.'
  ]
];
?>
<nav>
  <?php foreach ($pages as $page): ?>
    <a href="<?= $page['file'] ?>" <?= (isset($currentPage) && $currentPage === $page['file']) ? ' class="active"' : '' ?>><?= $page['label'] ?></a>
  <?php endforeach; ?>
</nav>
